### ISSUE TITLE
您好，Role-pointed Movie Narrator的完整代码什么时候可以发布？

### ISSUE THREAD

**Issue by JaylanMei** [yuezih/Movie101#1]
您好，Role-pointed Movie Narrator中的特征下载代码是空的，什么时候会发布完整的代码？

**Comment by yuezih** [comment]
您好，感谢您对Movie101的关注。我这两天才刚有时间整理开源，您现在看到的内容也是我今天凌晨刚刚发布的。我尽快把剩下的部分整理好，还请耐心等待。

**Comment by yuezih** [comment]
您好，特征已经通过TeraBox云盘release，如果您需要请自行下载，谢谢！
