### ISSUE TITLE
您好，请问可以提供预训练权重吗，请问有途径基于RMN实现单个视频的旁白生成吗？

### ISSUE THREAD

**Issue by Daria8976** [yuezih/Movie101#3]

**Comment by yuezih** [comment]
你好，感谢关注Movie101。我在RMN文件夹下新增了一个单个电影片段的inference脚本，并上传了我们训练的模型，希望对你有所帮助：
https://github.com/yuezih/Movie101/tree/main/baseline/RMN#inference

另外，RMN是我们提供的baseline，用的是非VLP模型，因此性能可能不尽人意，论文附录有一些case可以参考。
