### ISSUE TITLE
model not found

### ISSUE THREAD

**Issue by Beakboomboom** [yuezih/Movie101#5]
https://terabox.com/error/302.html
![image](https://github.com/yuezih/Movie101/assets/12118547/f2ac2041-7b69-4104-be26-c9083715ab3d)

**Comment by yuezih** [comment]
TeraBox cloud storage cannot be downloaded in China. I'm providing a [OneDrive link](https://1drv.ms/u/s!AocXJ7uKxt6Xg3O-QnnUINCuNOke?e=NoHWM9) for the model checkpoint.
